apiVersion: v2
name: securebank
description: SecureBank Banking Application Helm Chart
type: application
version: 1.0.0
appVersion: '2025.1'
maintainers:
  - name: DevOps Team
    email: devops@securebank.com

