apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: banking-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: ACCOUNT_ECR_IMAGE
          ports:
            - containerPort: 8080
